Repository openscilab/dmeta, pull requests merged in 2024-08, with the labels that each got.

#32 fix codecov badge issue (change to dev)
  README.md
Labels: bug, minor

#34 `README.md` modification
  CHANGELOG.md
  README.md
  TODO.md
Labels: documentation, minor

#35 `SECURITY.md`
  AUTHORS.md
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/RELEASE.md
  otherfiles/version_check.py
Labels: documentation, minor

#36 Feature/inplace
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  dmeta/__main__.py
  dmeta/functions.py
  tests/test_dmeta.py
Labels: new feature

#38 README.md updated
  README.md
Labels: documentation, enhancement

#37 Version 0.2
  CHANGELOG.md
  README.md
  SECURITY.md
  dmeta/params.py
  otherfiles/meta.yaml
  otherfiles/version_check.py
  setup.py
Labels: release
